### ISSUE TITLE
Bootstrapification pt3

### ISSUE THREAD

**Issue by myers** [new-day-international/reddit#184]
# sooner
- [x] spaces page: bottom align the "community since x" and size
- [x] manage space button in leftbar not what Jim wants yet. try icon on left, and use border rather than solid color
- [x] change follow's right bar to read "following"
- [x] See mock for how to make the following page have inline editing (the mocks are attached as images on #177)
- [x] #135
- [ ] ~~comment "cancel" button doesn't work~~ see: [30661170](https://github.com/new-day-international/reddit/issues/184#issuecomment-30661170)
- [x] http://localdev.lightnetb.org/message/inbox/ gives AttributeError: Subreddit(38).registration_fullname not found; it IS loaded and is NOT deleted.  Probably because some accounts don't have this information.
- [x] access info popup is in the wrong spot on the user options page
- [ ] ~~markdown on a space page right bar is not being used.  E.g alt-currency~~ see: [30662133](https://github.com/new-day-international/reddit/issues/184#issuecomment-30662133)
- [x] move the search bar and replace the jump to space text box in leftbar
- [x] after voting the arrow of your vote should change color, and the number should change color, make the unvoted state darker (see issue #157)
- [x] item list page: has a "reply" button that doesn't do anything.  Remove.
- [x] remove "Add new:" and new item button group found in rightbar
# later
- [ ] ~~truncate at the the word ending before 80 chars, rather than right at the 80th char~~ see: [30664335](https://github.com/new-day-international/reddit/issues/184#issuecomment-30664335)
- [x] show overlay of space rules when comment text box is shown (says it's done but not working for me)
- [ ] combined search bar that has suggests to search the site or jump to space by name later, or when doing site search return space results, or the basecamp model (as long as site search is the first option)
# leftovers
### Spaces Section /spaces/*
- [ ] House colorbar in general
- [ ] Search bar should have placeholder text like "search spaces"
- [ ] Search bar should have a hint like "enter 1 to 3 words that describe your interests"
- [ ] Switch back to the other search bar, yes?
- [ ] Figure out default image problem
### A space's page
- [ ] Compress the House Rules section "House: lightnet", clicking on the house name should uncollapse the rules listing.  Somewhere show a house color bar. in the collapsed section the house header icon should be shown.
- [ ] Item listing: two lines of most recent comment should be visible 
- [ ] On space pages the tab bar should be "items (with sort drop down when active), comments, files, wiki", this should be the same on a Item page as well.
### Rightbar:
- [ ] Compress the moderator section.  Should be able to message moderators at one click and expand the area to show a list of moderators.
- [ ] Subscribe/unsubscribe colors should really represent state (green for sub, grey for unsub)
### follow page
- [x] style
### options page
- [x] make votes public ofr everyone (check with Jim)
- [x] default yes to "allow my data to be use for research"
# jim's comments
# comment renders
- [x] Comment above render bars
- [x] Remove redundant wording
