### ISSUE TITLE
Bootstrapification 4

### ISSUE THREAD

**Issue by caseydriscoll** [new-day-international/reddit#186]
# Now
## item listing page
- [x] item listing page: inline comment mock is a go.  We should remove styling for stong, em, for two line comment preview.
- [x] item listing page: reword "Started 1 month ago by Flemming Funch [F]" to "Flemming Funch [F] posted 1 month ago"
- [x] set image to original author
## item page
- [x] Add a cancel button to the root comment
- [ ] ~~item page: Comment box: put overlay div with space/house rules that is hidden when clicked (and on a click the text area should be active)~~ [See 193](https://github.com/new-day-international/reddit/issues/193)
- [x] item page: "all 7 comments" remove if possible
- [ ] ~~item page: "email me new comments in this thread" move up to item button menu~~ [See 193](https://github.com/new-day-international/reddit/issues/193)
- [x] item page: buttons should light up if you are over the text of a comment (see current lightnet)
- [x] item page: buttons should light up if you are over the text of the item (see current lightnet)
- [ ] ~~Item page: Comment Sort button should be styled~~ [See 193](https://github.com/new-day-international/reddit/issues/193)
- [x] Item page: Comment Sort default to new
- [x] Item page: Comment Sort old -> oldest first, new -> newest first, either votes or best (research ) 
- [ ] ~~item page: comment voting: move point between triangles~~ [See 193](https://github.com/new-day-international/reddit/issues/193)
- [ ] ~~item page: commenting cancel button doesn't work~~ [See 193](https://github.com/new-day-international/reddit/issues/193)
- [x] Item page: leftbar: highlight space you are in 
- [x] item page: reply button everywhere should be blue like on the current lightnet.is styles
- [ ] ~~item page: top level comment does something fucked up~~ [See 193](https://github.com/new-day-international/reddit/issues/193)
- [x] Item page: vote arrows should be triangles
- [x] Clean up comments
## space page
- [x] space page: leftbar: highlight space you are in 
- [ ] ~~space page: rightbox: Add Box1, Box2, Box3 markdown rendered~~ [See 194](https://github.com/new-day-international/reddit/issues/194)
- [x] space specific page: "comments" tab -> "latest comments" tab
- [x] space page: moderator list unstyled
- [x] space page: remove space name from item listing
## space settings
- [x] Form too narrow
## spaces page
- [x] spaces page: "50 subscribers" and "A community for 3 months" on one line. Shorten text if it doesn't fit.
- [x] spaces page: move sub/unsub button to be on the same line as "email me new posts in this space" & other.  Shorten text to "email new posts", etc.
- [x] spaces page: shorter cards 
- [x] spaces page: subscribe button centered.  unsubscribe button over to the left and have checkboxes.
- [ ] ~~spaces page: top space: search bar and add space should be on the same line~~ No, [See 195](https://github.com/new-day-international/reddit/issues/195)
- [x] spaces page: show house color
- [x] spaces page: remove permission icons (requested by Jim on 2013-12-24)
- [x] spaces page: hover over house color, get popup with house rules (requested by Jim on 2013-12-24)
## messages page
- [x] Style
## misc
- [ ] ~~System user should have a registration fullname~~ [See 196](https://github.com/new-day-international/reddit/issues/196)
- [ ] ~~non logged in: leftbar: change labels "subscribed spaces" -> "pop. spaces", remove manage button.  Under multispaces should be "popular spaces" (default), "all", remove overs.~~ [See 197](https://github.com/new-day-international/reddit/issues/197)
- [ ] ~~search box: use a bootstrap popover to show the advanced help~~ No, [See 198](https://github.com/new-day-international/reddit/issues/198)
- [ ] ~~space editing page: Add Box1, Box2, Box3 inputs~~ [See 194](https://github.com/new-day-international/reddit/issues/194)
- [ ] ~~front page/ my subscribed: should a description in the right bar of what we are looking at (see /space/all and /space/follow)~~ Done? [See 199](https://github.com/new-day-international/reddit/issues/199)
# Leftovers
## from bootstrapification pt3
- [ ] ~~combined search bar that has suggests to search the site or jump to space by name later, or when doing site search return space results, or the basecamp model (as long as site search is the first option)~~ [See 200](https://github.com/new-day-international/reddit/issues/200)
### Jim's comments
- [x] Multispace highlighting in leftsidebar
- [x] Change rightsidebar bg coloring to gray (#f1f1f1)
- [x] Change rightsidebar headers to black on light gray
- [x] Reword item tagline in lists to remove redundant space location and last commenter
### Spaces Section /spaces/*
- [x] House colorbar in general
- [ ] ~~Search bar should have placeholder text like "search spaces"~~ [See 201](https://github.com/new-day-international/reddit/issues/201)
- [ ] ~~Search bar should have a hint like "enter 1 to 3 words that describe your interests"~~ [See 201](https://github.com/new-day-international/reddit/issues/201)
- [ ] ~~Switch back to the other search bar, yes?~~ [See 201](https://github.com/new-day-international/reddit/issues/201)
- [ ] ~~Figure out default image problem~~ [See 202](https://github.com/new-day-international/reddit/issues/202)
### A space's page
- [x] Compress the House Rules section "House: lightnet", clicking on the house name should uncollapse the rules listing.  Somewhere show a house color bar. ~~in the collapsed section the house header icon should be shown.~~ see: [30866101](https://github.com/new-day-international/reddit/issues/186#issuecomment-30866101)
- [x] Item listing: two lines of most recent comment should be visible 
- [x] On space pages the tab bar should be "items (with sort drop down when active), comments, files, wiki", this should be the same on a Item page as well.
### Rightbar:
- [ ] ~~Compress the moderator section.  Should be able to message moderators at one click and expand the area to show a list of moderators.~~ [See 203](https://github.com/new-day-international/reddit/issues/203)
- [x] Subscribe/unsubscribe colors should really represent state (green for sub, grey for unsub)
